app:
  image: goannotator-dev:latest
  ports:
    - "80:80"
    - "2345:2345"
  links:
    - "mongo:database"
  volumes:
    - "$GOPATH/src:/go/src"
  privileged: true
mongo:
  image: mongo:3
  ports:
    - "27017:27017"
  volumes:
    - "./data:/data/db"
